Repository konveyor/crane, pull requests merged in 2022-07, with the labels that each got.

#126 chore(workflows): configure github actions after updates
  .github/workflows/needs-triage.yaml
  .github/workflows/reconcile_gh_issue.yaml
Labels: lgtm, approved

#124 making sure ingress/route name does not exceed the allowed length
  cmd/transfer-pvc/transfer-pvc.go
  go.mod
  go.sum
Labels: lgtm, approved

#125 Crane sub-command to run function
  .github/workflows/go.yml
  cmd/runfn/runfn.go
  cmd/runfn/util.go
  go.mod
  go.sum
  internal/plugin/plugin_manager_helper_test.go
  main.go
Labels: kind/feature, lgtm, approved

#130 chore(workflows): require kind + priority + triage/accepted
  .github/workflows/reconcile_gh_issue.yaml
Labels: approved

#133 Set higher QPS and Burst defaults
  cmd/export/export.go
Labels: lgtm, approved

#114 Use rsync options struct to override the default rsync options in library
  .github/workflows/go.yml
  cmd/transfer-pvc/transfer-pvc.go
  go.mod
  go.sum
Labels: lgtm, approved

#136 crane sub-command to run krm functions
  .github/workflows/go.yml
  cmd/runfn/runfn.go
  cmd/runfn/util.go
  go.mod
  go.sum
  internal/plugin/plugin_manager_helper_test.go
  main.go
Labels: lgtm, approved

#134 Export everything using the PreferredVersion
  cmd/export/discover.go
  cmd/export/export.go
Labels: lgtm, approved

#139 Allow using a custom image for pvc-transfer
  cmd/transfer-pvc/transfer-pvc.go
  go.mod
  go.sum
Labels: lgtm, approved

#137 Allow searching multiple paths for plugins
  cmd/plugin-manager/add/add.go
  cmd/plugin-manager/list/list.go
  cmd/plugin-manager/plugin-manager.go
  cmd/plugin-manager/remove/remove.go
  cmd/transform/transform.go
  internal/plugin/plugin_helper.go
  internal/plugin/plugin_manager_helper.go
Labels: lgtm, approved

#140 feat: add new subcommand skopeo-sync-gen
  cmd/skopeo-sync-gen/skopeo-sync-gen.go
  main.go
Labels: lgtm, approved

#141 Progress reporting
  cmd/transfer-pvc/progress.go
  cmd/transfer-pvc/progress_test.go
  cmd/transfer-pvc/transfer-pvc.go
  cmd/transfer-pvc/transfer-pvc_test.go
  go.mod
  go.sum
Labels: lgtm, approved

#142 Allow restricting export using a label selector
  cmd/export/discover.go
  cmd/export/export.go
Labels: lgtm, approved

#143 Add transfer-pvc documentation
  cmd/transfer-pvc/README.md
Labels: lgtm, approved

#144 bug(export): should default label-selector to empty string
  cmd/export/export.go
Labels: lgtm, approved

#145 bug(transform): take optional-flags as JSON
  cmd/transform/transform.go
Labels: lgtm, approved
