Repository konveyor/crane, pull requests merged in 2022-06, with the labels that each got.

#104 Update .gitignore & owners
  .gitignore
  OWNERS
Labels: lgtm, approved

#93 add sseago to approvers
  OWNERS
Labels: lgtm, approved

#92 update cli doc to make it clear how to use slice/map params
  cmd/transform/transform.go
Labels: lgtm, approved

#80 Corrected the typo `crane export --help`
  cmd/export/export.go
Labels: lgtm, approved, needs-ok-to-test

#106 ci: use konveyor/github-actions to reconcile issues
  .github/workflows/reconcile_gh_issue.yaml
Labels: lgtm, approved

#107 chore: update templates to use new k8s style labels
  .github/ISSUE_TEMPLATE/RFE.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: lgtm, approved

#87 Integrating with pvc-transfer library
  cmd/transfer-pvc/transfer-pvc.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#108 remove alaypatel07 from owners
  OWNERS
Labels: lgtm, approved

#111 chore: drop extra gh workflow
  .github/workflows/jira_create_issue.yaml
Labels: lgtm, approved

#117 chore: add workflow for issues needing triage
  .github/workflows/needs-triage.yaml
Labels: lgtm, approved

#118 chore(workflows): Send digest tues/thurs
  .github/workflows/needs-triage.yaml
  .github/workflows/reconcile_gh_issue.yaml
Labels: lgtm, approved

#120 Update pvc-transfer dep
  go.mod
  go.sum
Labels: lgtm, approved

#121 bug: only run 1 at a time
  .github/workflows/reconcile_gh_issue.yaml
Labels: approved

#123 chore(workflows): reconcile only 1 issue at a time
  .github/workflows/reconcile_gh_issue.yaml
Labels: lgtm, approved
